spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(IATF3L3Or+I7CKxpdrvr+gcXYglRfUw/I94IiCZezPgXI1jSUgq/mOdDzkvY6RKsbFbV/tDXOQJJ5WLHv1o8BhJs/zEcQPktqIqd6J7OMEg=)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
